language: csharp
sudo: false

dotnet: 2.1.4 # SDK version; includes runtime version 2.0.5. Need 2.0+ for netcoreapp2.0 tests.
mono: 5.10.0 # Need 5.2+ for the included MSBuild.

solution: commercetools.NET.sln

matrix:
  include:
    - dotnet: 2.1.4
      env: DOTNETCORE=1
    - mono: 5.10.0
  allow_failures:
    - mono: 5.10.0


script:
  - ./build.sh --target=Travis
