language: csharp
mono: none
dotnet: 2.1.502

install:
  - dotnet restore --packages packages
  - dotnet user-secrets set "commercetools:ClientId" ${CTP_CLIENT_ID} --project commercetools.NET.Tests > /dev/null 2>&1
  - dotnet user-secrets set "commercetools:ClientSecret" ${CTP_CLIENT_SECRET} --project commercetools.NET.Tests > /dev/null 2>&1
  - dotnet user-secrets set "commercetools:ProjectKey" ${CTP_PROJECT_KEY} --project commercetools.NET.Tests > /dev/null 2>&1

script:
  - dotnet build -c Release
  - dotnet pack -c Release -o pack/
  - dotnet test commercetools.NET.Tests --no-build -c Release
